name: Build Statiq Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build statiq website
    steps:
      # Print out git config settings
      - name: Print out git config settings
        run: git config -l
      # Checkout codebase including submodules
      - name: Checkout code & submodules
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      # Set up .NET 6.0.x SDK
      - name: Setup .NET 6.0.x SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      # Build statiq website using dotnet run command
      - name: Build statiq website
        run: dotnet run
      # Upload build artifact from output directory
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: statiq-website
          path: ${{ github.workspace }}/output/**/*
